name: Java Push CI

on: 
 push:
   branches: '**'
 pull_request:
   branches: [master, develop]
 create:
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
      if: github.event_name != 'create' || github.event.ref_type != 'tag'

    - name: Test demo projects
      run: ./build-scripts/test.sh

    - name: Decrypt and import GPG key
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: bash ./build-scripts/decrypt_secret.sh
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Deploy to Maven OSSRH
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: bash ./build-scripst/deploy.sh
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
